apiVersion: v1
kind: Pod
metadata:
  name: longhorn-simple-pod
spec:
  containers:
    - name: volv
      image: nginx
      volumeMounts:
      - mountPath: /data
        name: mypd
  volumes:
    - name: volv
      persistentVolumeClaim:
        claimName: longhorn-simple-pvc
~                          
